### ISSUE TITLE
support scrubbing with arrows

### ISSUE THREAD

**Issue by blaineam** [LTVA1/flipper-zero-video-player#8]
Could you add a way to fast foward and rewind like a VHS player if you press and hold the right and left arrows?

**Comment by LTVA1** [comment]
Yeah I will add it when new Unleashed release is out. It's actually trivial to do, I know because I have seen wav player source code which does it

**Comment by blaineam** [comment]
Next unleashed firmware released a few days ago. Also noticed your app isn’t in the official flipper zero catalog on the mobile phone app. Any chance you’d add it to the official catalog?

**Comment by LTVA1** [comment]
Yes, I plan to work on this today. App isn't in catalog because I can't take screenshot via Flipper PC app since video player uses special fast API to draw on the screen with high FPS. So when I was adding my tracker to the catalog I didn't bother making my own screenshots in image editor, however, I may do it today. Also I will merge the pending PR, I hope.

**Comment by LTVA1** [comment]
Added fast forward and rewind. Displays a small progress bar and properly stops at beginning or end of the video. Try yourself. If it works, you can close this issue. If it doesn't, report it here (I mean, it works for me, but may not work for you because of whatever reason)

**Comment by blaineam** [comment]
works nicely thank you!
